- name: variables file
  hosts: web
  vars_files:
  - vars.yml
  tasks:
  - name: printing the information 
    ansible.builtin.debug:
      msg: "I am practicing {{COURSE}}, with duration of {{DURATION}} under the guidance of {{TRAINER}}."