- name: variable preferences
  hosts: web
  # vars:
  #   COURSE: "Shell"
  vars_files:
  - vars.yml
  # vars_prompt:
  # - name: COURSE
  #   prompt: Please enter your course
    #private: false 
  tasks:
  - name: printing the information
    vars:
   # - COURSE: "git"
    ansible.builtin.debug:
      msg: "I am practicing {{COURSE}}."



#1.Arguments
#2.task level
#3.vars_files
#4.prompt
#5.play level
#6.inventory