- name: variable preferences
  hosts: web
  vars:
    COURSE: "Shell"
  vars_files:
  - vars.yml
  vars_prompt:
  - name: COURSE
    prompt: Please enter your course
    private: false 
  tasks:
  - name: printing the information
    vars:
    - DURATION: "15Hrs"
    ansible.builtin.debug:
      msg: "I am practicing {{COURSE}}."