- name: conditions
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: Please enter your number
    private: false
  
  tasks:
  - name: print the msg
    ansible.builtin.debug:
      msg: "number is less than 10"
    when: number | int < 10 
  
  - name: print the msg
    ansible.builtin.debug:
      msg: "Please enter your number"
    when: number | int >= 10 