- name: installing nginx
  hosts: web
  become: yes
  tasks:
  - name: printing gathered facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"

  - name: installing nginx for redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"
    when: state == absent

  - name: installing nginx for debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "debian"
