- name: command vs shell
  hosts: local
  connection: local
  tasks:
  - name: execute the command
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
  
  - name: search the process
    ansible.builtin.shell: ps -ef | grep ssh
    register: output
  
  - name: printing output
    ansible.builtin.debug:
      msg: "{{ output }}"
  
  - name: search the process
    ansible.builtin.command: ps -ef | grep ssh
    register: output_1
  
  - name: printing output
    ansible.builtin.debug:
      msg: "{{ output_1 }}"